version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: DoCheckerElasticSearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  web:
    build:
      dockerfile: ./Dockerfile
    container_name: DoCheckerWeb
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
  kibana:
    container_name: DoCheckerKibana
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports:
      - "5601:5601"


volumes:
  elasticsearch-data:
    driver: local


